# Generated by Django 5.0.1 on 2024-01-25 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название организации')),
            ],
        ),
        migrations.CreateModel(
            name='TnvedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Код товара')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_status_legal', models.CharField(choices=[('+', 'Разрешен'), ('-', 'Без лицензии'), ('x', 'Запрещен')], default='-', max_length=1, verbose_name='Статус ввоза для юридических лиц')),
                ('import_status_individual', models.CharField(choices=[('+', 'Разрешен'), ('-', 'Без лицензии'), ('x', 'Запрещен')], default='-', max_length=1, verbose_name='Статус ввоза для физических лиц')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnvedcode.organization')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tnvedcode.tnvedcode')),
            ],
        ),
    ]
