# Generated by Django 5.0.1 on 2024-01-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnvedcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='import_status_individual',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('x', 'x')], default='-', max_length=1, verbose_name='Статус ввоза для физических лиц'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='import_status_legal',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('x', 'x')], default='-', max_length=1, verbose_name='Статус ввоза для юридических лиц'),
        ),
    ]
