# Generated by Django 5.0.1 on 2024-01-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnvedcode', '0002_alter_permission_import_status_individual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnvedcode',
            name='group_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Наименование группы товара'),
            preserve_default=False,
        ),
    ]
