# Generated by Django 5.0.1 on 2024-01-26 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnvedcode', '0003_tnvedcode_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tnvedcode',
            old_name='group_name',
            new_name='name',
        ),
    ]
