# Generated by Django 5.0.1 on 2024-01-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tnvedcode', '0004_rename_group_name_tnvedcode_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('code', 'organization')},
        ),
    ]
